name: Branch is up-to-date

on:
  pull_request:
    branches:
      - '*'

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          BASE_BRANCH="origin/main"
          CURRENT_BRANCH=$(git branch --show-current)
          if ! git merge-base --is-ancestor $BASE_BRANCH ${{ github.event.pull_request.head.sha }}; then
            echo "Error: The current branch is not based on $BASE_BRANCH."
            exit 1
          fi
